名称:带咕噜的NodeJS

开启:
推送:
分支:[ "主要" ]
拉取请求:
分支:[ "主要" ]

工作:
构建:
运行:Ubuntu-最新版

策略:
矩阵:
节点版本:[18.x、20.x、22.x]

步骤:
- 使用: actions/checkout@v4

    - 名字: 使用Node.js ${{矩阵.节点-版本}}
使用: 动作/设置-节点@v4
随着:
节点版本: ${{矩阵.节点-版本}}

    - 名字: 建设
奔跑: |
npm安装
咕哝
